spring:
  application:
    name: main
minio:
  secret-key: "minioadmin"
  access-key: "minioadmin"
  bucket-name: "bucket"
  endpoint: "http://localhost:9000"
voxelizator:
  endpoint: "http://localhost:5454"